# Generated by Django 3.2.16 on 2023-03-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_tran_report', '0003_alter_transaction_user_info_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_info_uid',
            new_name='uid',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('id', 'uid')},
        ),
    ]
