# Generated by Django 3.2.16 on 2023-03-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('un_tran_report', '0004_auto_20230313_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='un_tran_report.userinfo'),
        ),
    ]
