# Generated by Django 3.2.16 on 2023-03-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_tran_report', '0006_alter_transaction_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='uid',
            new_name='user_info_uid',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('id', 'user_info_uid')},
        ),
    ]
